import { ProductosContext } from "./ProductosContext";

export const ProductosProvider = ({ children }) => {
  const productos = [
    {
      id: 1,
      nombre: "Procesador Intel Core i9-13900K",
      categoria: "CPU",
      marca: "Intel",
      precio: 589.99,
      stock: 15,
      caracteristicas: [
        "24 núcleos",
        "5.8 GHz Turbo",
        "Socket LGA1700",
        "DDR5",
      ],
      compatibilidad: ["PC de escritorio"],
      garantiaMeses: 36,
    },
    {
      id: 2,
      nombre: "GeForce RTX 4090",
      categoria: "GPU",
      marca: "NVIDIA",
      precio: 1599.99,
      stock: 8,
      caracteristicas: ["24 GB GDDR6X", "DLSS 3", "Ray Tracing", "PCIe 4.0"],
      compatibilidad: ["PC de escritorio"],
      garantiaMeses: 36,
    },
    {
      id: 3,
      nombre: "Corsair Vengeance RGB 32GB",
      categoria: "RAM",
      marca: "Corsair",
      precio: 129.99,
      stock: 42,
      caracteristicas: ["DDR5 5600MHz", "CL36", "RGB", "Kit 2x16GB"],
      compatibilidad: ["PC de escritorio", "Laptops gaming"],
      garantiaMeses: 60,
    },
    {
      id: 4,
      nombre: "Samsung 980 Pro 1TB",
      categoria: "Almacenamiento",
      marca: "Samsung",
      precio: 99.99,
      stock: 25,
      caracteristicas: [
        "NVMe PCIe 4.0",
        "7000 MB/s lectura",
        "5000 MB/s escritura",
        "M.2 2280",
      ],
      compatibilidad: ["PC de escritorio", "Laptops", "PS5"],
      garantiaMeses: 60,
    },
    {
      id: 5,
      nombre: "Logitech MX Keys",
      categoria: "Periférico",
      marca: "Logitech",
      precio: 99.99,
      stock: 37,
      caracteristicas: [
        "Teclado inalámbrico",
        "Iluminación inteligente",
        "Multidispositivo",
        "Teclas esculpidas",
      ],
      compatibilidad: ["PC", "Mac", "Tablets"],
      garantiaMeses: 24,
    },
    {
      id: 6,
      nombre: "ASUS ROG Strix Z790-E",
      categoria: "Placa base",
      marca: "ASUS",
      precio: 499.99,
      stock: 12,
      caracteristicas: ["Socket LGA1700", "DDR5", "WiFi 6E", "PCIe 5.0", "RGB"],
      compatibilidad: ["PC de escritorio"],
      garantiaMeses: 36,
    },
    {
      id: 7,
      nombre: "Dell XPS 15 9530",
      categoria: "Laptop",
      marca: "Dell",
      precio: 2499.99,
      stock: 7,
      caracteristicas: [
        "Intel Core i7-13700H",
        "32GB RAM",
        "1TB SSD",
        "RTX 4070",
        "OLED 3.5K",
      ],
      compatibilidad: [],
      garantiaMeses: 24,
    },
    {
      id: 8,
      nombre: "Noctua NH-D15",
      categoria: "Refrigeración",
      marca: "Noctua",
      precio: 109.99,
      stock: 28,
      caracteristicas: [
        "Doble ventilador",
        "6 heatpipes",
        "Silencioso",
        "Compatible AM5/LGA1700",
      ],
      compatibilidad: ["PC de escritorio"],
      garantiaMeses: 72,
    },
    {
      id: 9,
      nombre: "Corsair RM850x",
      categoria: "Fuente de alimentación",
      marca: "Corsair",
      precio: 149.99,
      stock: 19,
      caracteristicas: [
        "850W 80 Plus Gold",
        "Modular",
        "Ventilador silencioso",
        "Cables trenzados",
      ],
      compatibilidad: ["PC de escritorio"],
      garantiaMeses: 120,
    },
    {
      id: 10,
      nombre: "Samsung Odyssey G9",
      categoria: "Monitor",
      marca: "Samsung",
      precio: 1299.99,
      stock: 6,
      caracteristicas: [
        "49' Super UltraWide",
        "DQHD (5120x1440)",
        "240Hz",
        "Curvo 1000R",
        "QLED",
      ],
      compatibilidad: ["PC", "Consolas"],
      garantiaMeses: 24,
    },
  ];
  return (
    <ProductosContext.Provider value={{ productos }}>
      {children}
    </ProductosContext.Provider>
  );
};
